### ISSUE TITLE
mvn install fails on MacOS Ventura

### ISSUE THREAD

**Issue by stormqueen1990** [wildfly-security/wildfly-openssl-natives#28]
Running `mvn install` on MacOS Ventura to generate the native artifacts currently fails due to a mismatch between the prototype function signatures and the actual function signatures. `make` generates the following error message:
```make
../libwfssl/src/threads.c:154:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
void ssl_thread_setup()
                     ^
                      void
1 error generated.
make: *** [target/threads.o] Error 1
[ERROR] Command execution failed.
```

**Comment by fjuma** [comment]
I've created https://issues.redhat.com/browse/SSLNTV-38 to track this so am going to close this GitHub issue.

Thank you very much for reporting this!
